#!/usr/bin/env bash
set -euo pipefail

: "${DB_HOST:=db}"
: "${DB_PORT:=3306}"
: "${MYSQL_DATABASE:=blackcore}"
: "${MYSQL_USER:=blackcore}"
: "${MYSQL_PASSWORD:?MYSQL_PASSWORD is required}"
: "${INTERSERVER_USER:=blackcore_inter}"
: "${INTERSERVER_PASSWORD:?INTERSERVER_PASSWORD is required}"
: "${PUBLIC_IP:?PUBLIC_IP is required}"

cd /opt/blackcore
mkdir -p conf/import log

echo "[Black Core] Waiting for MariaDB at ${DB_HOST}:${DB_PORT}..."
for i in $(seq 1 90); do
  if mariadb-admin ping -h"${DB_HOST}" -P"${DB_PORT}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" --silent >/dev/null 2>&1; then
    break
  fi
  if [ "$i" -eq 90 ]; then
    echo "[Black Core] MariaDB did not become ready." >&2
    exit 1
  fi
  sleep 2
done

# Replace rAthena's sample s1/p1 inter-server account with deployment credentials.
INTERSERVER_USER_SQL=${INTERSERVER_USER//\'/\'\'}
INTERSERVER_PASSWORD_SQL=${INTERSERVER_PASSWORD//\'/\'\'}
mariadb -h"${DB_HOST}" -P"${DB_PORT}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" <<SQL
UPDATE login
SET userid='${INTERSERVER_USER_SQL}', user_pass='${INTERSERVER_PASSWORD_SQL}', sex='S'
WHERE account_id=1;
SQL

cat > conf/import/inter_conf.txt <<CONF
// Generated by Black Core container entrypoint.
party_share_level: 20
login_server_ip: ${DB_HOST}
login_server_port: ${DB_PORT}
login_server_id: ${MYSQL_USER}
login_server_pw: ${MYSQL_PASSWORD}
login_server_db: ${MYSQL_DATABASE}
char_server_ip: ${DB_HOST}
char_server_port: ${DB_PORT}
char_server_id: ${MYSQL_USER}
char_server_pw: ${MYSQL_PASSWORD}
char_server_db: ${MYSQL_DATABASE}
map_server_ip: ${DB_HOST}
map_server_port: ${DB_PORT}
map_server_id: ${MYSQL_USER}
map_server_pw: ${MYSQL_PASSWORD}
map_server_db: ${MYSQL_DATABASE}
log_db_ip: ${DB_HOST}
log_db_port: ${DB_PORT}
log_db_id: ${MYSQL_USER}
log_db_pw: ${MYSQL_PASSWORD}
log_db_db: ${MYSQL_DATABASE}
CONF

cat > conf/import/char_conf.txt <<CONF
server_name: BlackCore-Ascension
wisp_server_name: BlackCore
userid: ${INTERSERVER_USER}
passwd: ${INTERSERVER_PASSWORD}
login_ip: 127.0.0.1
bind_ip: 0.0.0.0
char_ip: ${PUBLIC_IP}
char_port: 6121
CONF

cat > conf/import/map_conf.txt <<CONF
userid: ${INTERSERVER_USER}
passwd: ${INTERSERVER_PASSWORD}
char_ip: 127.0.0.1
bind_ip: 0.0.0.0
map_ip: ${PUBLIC_IP}
map_port: 5121
CONF

cat > conf/import/login_conf.txt <<CONF
bind_ip: 0.0.0.0
login_port: 6900
CONF

cleanup() {
  echo "[Black Core] Shutting down..."
  ./athena-start stop || true
}
trap cleanup TERM INT

./athena-start start --enlog

# Keep the container alive while supervising all three server processes.
while true; do
  for srv in login-server char-server map-server; do
    pidfile=".${srv}.pid"
    if [ ! -f "$pidfile" ] || ! kill -0 "$(cat "$pidfile")" 2>/dev/null; then
      echo "[Black Core] ${srv} stopped unexpectedly." >&2
      exit 1
    fi
  done
  sleep 5
done
